controller:
  replicas: 1
  nodeSelector:
    argocd: "true"

server:
  replicas: 1
  nodeSelector:
    argocd: "true"

repoServer:
  nodeSelector:
    argocd: "true"

applicationSet:
  enabled: true
  nodeSelector:
    argocd: "true"

dex:
  enabled: false

notifications:
  enabled: false

redis:
  enabled: true
  nodeSelector:
    argocd: "true"
