api:
  dashboard: true

deployment:
  replicas: 1
  podAnnotations: {}
  nodeSelector:
    ingress: "true"

hostNetwork: true

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true
  # Later secure this with auth or TLS

service:
  type: ClusterIP

logs:
  general:
    level: WARN
  access:
    enabled: true