api:
  dashboard: true

deployment:
  replicas: 1
  podAnnotations: {}
  
nodeSelector:
  ingress: "true"
  
ports:
  web:
    redirectTo: websecure
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true

tls:
  stores:
    default:
      defaultCertificate:
        secretName: traefik-cert

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.178.220

logs:
  general:
    level: WARN
  access:
    enabled: true