# apps/websites/buffalo/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buffalo-site
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: websites
spec:
  project: default
  source:
    repoURL: https://github.com/Kamikaetzchen/raspi-cluster.git
    targetRevision: HEAD
    path: k8s/apps/websites/buffalo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true