apiVersion: apps/v1
kind: Deployment
metadata:
  name: buffalo-site
  namespace: websites
  labels:
    app: buffalo-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buffalo-site
  template:
    metadata:
      labels:
        app: buffalo-site
    spec:
      containers:
      - name: buffalo-site
        image: nginx:alpine
        volumeMounts:
        - name: buffalo-content
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      initContainers:
      - name: fetch-buffalo-content
        image: amazon/aws-cli:2.15.19
        command:
        - sh
        - -c
        - >
          aws --endpoint-url http://192.168.178.102:9000 s3 sync s3://buffalo /buffalo
        envFrom:
        - secretRef:
            name: minio-credentials
        volumeMounts:
        - name: buffalo-content
          mountPath: /buffalo
      volumes:
      - name: buffalo-content
        emptyDir: {}